CVProof.Web.Proto/Controllers/ContractController.cs
using CVProof.DAL.ETH;
using CVProof.DAL.SQL;
using CVProof.DAL.AWS;
using CVProof.Export.PDF;
using CVProof.Models;
using CVProof.Utils;
using CVProof.Web.Models;

using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;

using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlClient;
using System.Diagnostics;
using System.IdentityModel.Tokens.Jwt;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using System.Net.Http.Headers;
using System.Net.Http;

namespace CVProof.Web.Controllers
{
    public class ContractController : BaseController
    {
        public ContractController(IConfiguration configuration, IUserMgr user) : base(configuration, user){}

        [AllowAnonymous]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize]
        public IActionResult Validate()
        {
            if (_user.IsAuthenticated) { ViewBag.User = _user.User; ViewBag.Roles = _user.Roles; }

            ValidateViewModel model = new ValidateViewModel();
            
            ViewData["Title"] = "Validate";

            return View(model);
        }

        [Authorize]
        [HttpPost]
        public async Task SaveFile(ValidateViewModel model)
        {           
            HeaderModel header = new HeaderModel();
            
            header.IssuerUuid = _user.User;
            header.IssuerName = SQLData.GetProfileById(_user.User).Name;
            
            if (String.IsNullOrEmpty(model.Validator))
            {
                header.ValidatorUuid = header.IssuerUuid;
                header.ValidatorName = header.IssuerName;
            }
            else
            {
                header.ValidatorName = model.Validator;              
            }

            header.Category = Category.File.ToString();
            header.Stored = model.StoreFile;            

            try
            {
                var file = model.Files[0];
                var attachment = model.Attachment;
                
                header.Init();
                header.HeaderId = Utils.Convert.ToHexString(header.GetSimpleHashBytes());

                if (file != null && file.Length > 0)
                {
                    byte[] sourceFile;                      

                    using (MemoryStream stream = new MemoryStream())
                    {
                        await file.CopyToAsync(stream);
                        sourceFile = stream.ToArray();
                    }

                    if (model.StoreFile)
                    {
                        #region stamping

                        byte[] stampedFile;

                        try
                        {                                    
                            stampedFile = await GetPDF(sourceFile, header.HeaderId);
                        }
                        catch(Exception e)
                        {
                            stampedFile = sourceFile;
                        }

                        #endregion

                        #region hash
                        using (System.Security.Cryptography.HashAlgorithm sha256 = System.Security.Cryptography.SHA256.Create())
                        {
                            header.DataHash = Utils.Convert.ToHexString(sha256.ComputeHash(stampedFile));
                        }
                        #endregion

                        #region store
                        using (MemoryStream stream = new MemoryStream(stampedFile))
                        {
                            S3.Init(_configuration["accessKey"], _configuration["secretKey"], _configuration["storageBucket"]);
  
                            await S3.WriteObject(stream, header.HeaderId, file.ContentType);
                        }
                        #endregion

                        if (model.Attachment != null)
                        {
                            byte[] attachmentFile;

                            using (MemoryStream stream = new MemoryStream())
                            {
                                await attachment.CopyToAsync(stream);
                                attachmentFile = stream.ToArray();
                            }

                            #region init
                            HeaderModel attachmentHeader = new HeaderModel();
                            attachmentHeader.Init();
                            attachmentHeader.HeaderId = Utils.Convert.ToHexString(attachmentHeader.GetSimpleHashBytes());
                            attachmentHeader.ValidatorName = model.Validator;
                            attachmentHeader.IssuerName = model.Validator;
                            attachmentHeader.IssuerUuid = _user.User;
                            attachmentHeader.Category = Category.Attachment.ToString();                            
                            attachmentHeader.Stored = true;
                            #endregion

                            #region hash
                            using (System.Security.Cryptography.HashAlgorithm sha256 = System.Security.Cryptography.SHA256.Create())
                            {
                                attachmentHeader.DataHash = Utils.Convert.ToHexString(sha256.ComputeHash(attachmentFile));
                            }
                            #endregion

                            #region store
                            using (MemoryStream stream = new MemoryStream(attachmentFile))
                            {
                                await S3.WriteObject(stream, attachmentHeader.HeaderId, attachment.ContentType);
                            }
                            #endregion

                            header.Attachment = attachmentHeader.HeaderId;
                            SQLData.InsertHeader(attachmentHeader);
                        }
                    }
                    else
                    {
                        using (System.Security.Cryptography.HashAlgorithm sha256 = System.Security.Cryptography.SHA256.Create())
                        {
                            header.DataHash = Utils.Convert.ToHexString(sha256.ComputeHash(sourceFile));
                        }                                
                    }                        

                    header.GlobalHash = Utils.Convert.ToHexString(header.GetFullHashBytes());

                    SQLData.InsertHeader(header);                    
                }                
            }

            catch (Exception e)
            {
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<HeaderViewModel> Validate([FromBody] HashDto dto)
        {
            if (_user.IsAuthenticated) { ViewBag.User = _user.User; ViewBag.Roles = _user.Roles; }

            HeaderModel header = SQLData.GetHeaderById(dto.hash);
            
            UserProfileModel validatorProfile = SQLData.GetProfileById(_user.User);

            header.ValidatorUuid = validatorProfile.Id;
            header.ValidatorName = validatorProfile.Name;

            if (String.IsNullOrEmpty(header.ValidatorLegitimationId) || String.IsNullOrEmpty(header.IssuerUuid))
            {                
                header.IssuerUuid = validatorProfile.Id;
                header.IssuerName = validatorProfile.Name;
            }

            header.ValidationCounter = "1";

            string contractAddress = _configuration["ethContractAddress"];
            string abi = _configuration["ethAbi"];
            string senderAddress = _configuration["ethSenderAddress"];
            string senderPrimaryKey = _configuration["ethSenderPK"];

            string ethNode = _configuration["ethNode"];

            Ethereum eth = new Ethereum(contractAddress,abi,senderAddress,senderPrimaryKey,ethNode);

            header = await eth.SendToNetwork(header);

            SQLData.UpdateHeader(header);

            header = SQLData.GetHeaderWithImageById(header.HeaderId);

            return new HeaderViewModel(header, _configuration);            
        }

        [Authorize]
        [HttpPost]
        public async Task<bool> DeleteDoc(string id)
        {
            HeaderModel header = SQLData.GetHeaderById(id);

            if (header != null)
            {
                if (String.IsNullOrEmpty(header.Attachment))
                {
                    SQLData.DeleteDoc(header.Attachment);
                    S3.DeleteObject(header.Attachment);                
                }

                SQLData.DeleteDoc(id);
                S3.DeleteObject(id);
            }

            return true;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Verify(CertificateViewModel model = null)
        {
            if (_user.IsAuthenticated) { ViewBag.User = _user.User; ViewBag.Roles = _user.Roles; }
            ViewData["Title"] = "Verify";

            return View(model ?? new CertificateViewModel());
        }

        [AllowAnonymous]
        [HttpPost]
        public async Task<bool> VerifyCertificateFile(VerifyViewModel model)
        {
            bool ret = false;

            byte[] datahash;

            try
            {
                datahash = null;


CVProof.Web.Proto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CVProof.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/bootstrap-imageupload.css" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-imageupload.min.css" />
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    </environment>    
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="http://token-certificate.fileproof.org/" class="navbar-brand">CVProof.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="validate" class="hide"><a asp-area="" asp-controller="Contract" asp-action="Validate">Validate</a></li>
                    <li id="verify"><a asp-area="" asp-controller="Contract" asp-action="Upload">Verify</a></li>
                    <li id="docs" class="hide"><a asp-area="" asp-controller="Contract" asp-action="ShowDocs">Documents</a></li>                    
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CVProof.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-1.9.1.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/bootstrap-imageupload.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>        
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.1.min.js"
                asp-fallback-src="~/lib/jquery/jquery-1.9.1.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-EaUkI/FiMJtEXWAl0dCczvbFvjfzsIF1UNKGJvu9p5JIG71Kih7/kQJvYbBL7HOn">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/bootstrap-imageupload.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>        
    </environment>    

    <script type="text/javascript">
        $(updatecontrols());
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CVProof.Web.Proto/Views/Shared/_LayoutNoPadding.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CVProof.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/bootstrap-imageupload.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/bootstrap-imageupload.min.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div style="padding-top:6px">
                <a href="https://fileproof.org"><img src="~/images/fileproof_logo.png" height="36" /></a>
            </div>
        </div>
    </nav>
    <div style="text-align:center;width:100%">
        <div style="display:inline-block;">
            <img src="~/images/cert-logo.png" style="display:inline-block; padding:15px" />
        </div>
    </div>
    <div class="container-fluid" style="margin:0px; text-align:center; padding:0px; display:flex;">
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery-1.9.1.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.1.min.js"
                asp-fallback-src="~/lib/jquery/jquery-1.9.1.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-EaUkI/FiMJtEXWAl0dCczvbFvjfzsIF1UNKGJvu9p5JIG71Kih7/kQJvYbBL7HOn">
        </script>

        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script type="text/javascript">
        $(updatecontrols());
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>